# Generated by Django 5.1.5 on 2025-01-21 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع مدرک شناسایی',
                'verbose_name_plural': 'نوع مدرک شناسایی',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فارسی شرکت خارجی')),
                ('en_name', models.CharField(max_length=100, verbose_name='نام لاتین شرکت خارجی')),
                ('register_number', models.PositiveSmallIntegerField(verbose_name='شماره ثبت شرکت')),
                ('company_type', models.CharField(max_length=50, verbose_name='نوع شرکت')),
                ('registered_country', models.CharField(max_length=50, verbose_name='کشور محل ثبت')),
                ('registered_date', models.DateField(verbose_name='تاریخ ثبت')),
                ('registered_from', models.CharField(max_length=50, verbose_name='تابعیت ثبتی شرکت')),
                ('owner_type', models.CharField(max_length=50, verbose_name='نوع مالکیت')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.PositiveSmallIntegerField(verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('identifier', models.PositiveIntegerField(verbose_name='شناسه فروشنده خارجی')),
                ('created_at', models.DateField(verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200c',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('identifier', models.PositiveIntegerField(verbose_name='شناسه فروشنده خارجی')),
                ('created_at', models.DateField(verbose_name='تاریخ ایجاد')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام/ First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی/ Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('mother_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='نام مادر')),
                ('grandfather_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='نام جد')),
                ('country', models.CharField(max_length=50, verbose_name='کشور محل تولید')),
                ('city', models.CharField(blank=True, default=None, max_length=50, verbose_name='شهر محل تولد')),
                ('sex', models.CharField(choices=[('mail', 'مرد'), ('fmail', 'زن')], max_length=5, verbose_name='جنسیت')),
                ('birthday', models.DateField(verbose_name='تاریخ تولید')),
                ('nationality', models.CharField(max_length=50, verbose_name='ملیت')),
                ('maried', models.CharField(max_length=50, verbose_name='وضعیت تاهل')),
                ('personal_image', models.ImageField(upload_to='uploads/overseas_supplier/', verbose_name='تصویر پرسنلی')),
                ('document_number', models.CharField(max_length=100, verbose_name='شماره مدرک شناسایی')),
                ('create_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expire_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overseas_supplier.documenttype', verbose_name='نوع مدرک شناسایی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'شخص حقیقی',
                'verbose_name_plural': 'شخص حقیقی',
            },
        ),
    ]
