# Generated by Django 5.1.5 on 2025-01-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('overseas_supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='create_date',
            new_name='issue_date',
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.country', verbose_name='کشور محل تولد'),
        ),
    ]
