# Generated by Django 5.1.5 on 2025-01-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('overseas_supplier', '0002_rename_create_date_person_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='person',
            name='maried',
            field=models.CharField(choices=[('s', 'مجرد'), ('m', 'متاهل'), ('c', 'متارکه'), ('w', 'بیوه')], max_length=50, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natinality_country', to='dashboard.country', verbose_name='ملیت'),
        ),
    ]
