# Generated by Django 5.1.5 on 2025-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0003_rename_sex_person_gender_alter_person_maried_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_image',
            field=models.ImageField(blank=True, default=None, max_length=1000, upload_to='uploads/overseas_supplier/', verbose_name='تصویر پرسنلی'),
        ),
    ]
