# Generated by Django 5.1.5 on 2025-01-22 14:34

import extensions.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0004_alter_person_birthday_alter_person_personal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.PositiveIntegerField(default=functools.partial(extensions.utils.generate_random_number, *(13,), **{}), verbose_name='شناسه فروشنده خارجی'),
        ),
    ]
