# Generated by Django 5.1.5 on 2025-01-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas_supplier', '0005_alter_person_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
