# Generated by Django 5.1.5 on 2025-01-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('overseas_supplier', '0007_companyownertype_companysubject_companytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='dashboard.country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='overseas_supplier.companyownertype', verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_number',
            field=models.PositiveSmallIntegerField(verbose_name='شماره ثبت'),
        ),
    ]
