# Generated by Django 5.1.5 on 2025-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='uploads/users/avatar', verbose_name='تصویر پرسنلی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='use_2fa',
            field=models.BooleanField(default=False, verbose_name='مایل به استفاده از رمز دو عاملی هستم'),
        ),
    ]
