# Generated by Django 5.1.5 on 2025-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_uuid_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='اعتبار سنجی شماره موبایل'),
        ),
    ]
