# Generated by Django 5.1.5 on 2025-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar_alter_customuser_use_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/users/avatar', verbose_name='تصویر پرسنلی'),
        ),
    ]
