# Generated by Django 5.1.5 on 2025-01-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_mobile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_verified',
        ),
    ]
