# Generated by Django 5.1.5 on 2025-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_options_alter_userrole_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='base',
            field=models.BooleanField(default=True, verbose_name='پایه حقیقی/حقوقی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_business_card',
            field=models.BooleanField(default=False, verbose_name='بازرگان حقیقی/ حقوقی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_internal_trader',
            field=models.BooleanField(default=False, verbose_name='تاجر حقیقی/ حقوقی'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
