# Generated by Django 5.1.5 on 2025-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userrole_role_remove_userrole_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='base',
            field=models.BooleanField(default=True, verbose_name='پایه حقیقی / حقوقی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_business_card',
            field=models.BooleanField(default=False, verbose_name='بازرگان حقیقی / حقوقی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_internal_trader',
            field=models.BooleanField(default=False, verbose_name='تاجر حقیقی / حقوقی'),
        ),
    ]
