# Generated by Django 5.1.5 on 2025-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('br', 'پایه حقیقی / حقوقی'), ('bc', 'بازرگانی حقیقی / حقوقی'), ('it', 'تاجر حقیقی /حقوقی')], default='br', max_length=2, verbose_name='نقش فعال'),
        ),
    ]
