# Generated by Django 5.1.5 on 2025-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور',
            },
        ),
    ]
