# Generated by Django 5.1.5 on 2025-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=250, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(blank=True, default=None, max_length=100, verbose_name='شناسه جهانی قلم کالا')),
                ('hs_code', models.CharField(max_length=100, verbose_name='کد HS')),
                ('isic', models.CharField(blank=True, default=None, max_length=100, verbose_name='کد ISIC')),
                ('cpc', models.CharField(blank=True, default=None, max_length=100, verbose_name='کد CPC')),
                ('identitie', models.PositiveSmallIntegerField(blank=True, default=None, verbose_name='شناسه')),
                ('mandatory_descriptive_field', models.JSONField(verbose_name='فیدهای توصیفی اجباری')),
                ('optional_fields', models.JSONField(verbose_name='فیلدهای اختیاری')),
                ('count_unit', models.CharField(max_length=50, verbose_name='واحد شمارش')),
            ],
            options={
                'verbose_name': 'شناسه کالا',
                'verbose_name_plural': 'شناسه کالا',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سرفصل')),
                ('en_title', models.CharField(max_length=250, verbose_name='کتگوری')),
                ('featue_image', models.ImageField(max_length=500, upload_to='uploads/product_identifier', verbose_name='تصویر کالا')),
                ('description', models.TextField(verbose_name='تعریف سرفصل')),
                ('message', models.TextField(verbose_name='هشدار')),
                ('code', models.PositiveSmallIntegerField(verbose_name='کد سرفصل')),
                ('gtin', models.JSONField(verbose_name='شناسه جهانی کالا(GTIN)')),
                ('hs', models.JSONField(verbose_name='کد HS')),
                ('isic', models.JSONField(verbose_name='کد ISIC')),
                ('count_unit', models.JSONField(verbose_name='واحد شمارش')),
                ('mandatory_descriptive_field', models.JSONField(verbose_name='فیلدهای توصیفی اجباری')),
                ('optional_fields', models.JSONField(verbose_name='فیلدهای اختیاری')),
                ('category', models.ManyToManyField(to='product_identifier.productcategory', verbose_name='دسته\u200cبندی(ها)')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا',
            },
        ),
    ]
