# Generated by Django 5.1.5 on 2025-01-19 15:43

import django.db.models.deletion
import upload_qualifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.PositiveIntegerField(default=upload_qualifications.models.generate_random_number, verbose_name='شماره درخواست')),
                ('request_type', models.CharField(default='صدور', max_length=50, verbose_name='نوع درخواست')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('status', models.CharField(choices=[('FC', 'تایید نهایی')], default='FC', max_length=5, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارت بازرگانی',
                'verbose_name_plural': 'کارت\u200cهای بازرگانی',
            },
        ),
    ]
